describe('Operações Simples', () => {
    beforeAll(() => {
        this.elementos = carregarConteudo()
        this.$resultado = this.elementos['calc'].querySelector('input')
        initCalculadora()
    })
    beforeEach(() => {
        this.$resultado.value = ''
    })
    describe('Soma', () => {
        it('Somar 7 + 5 deve resultar em 12', () => {
            this.elementos[7].click()
            this.elementos['+'].click()
            this.elementos[5].click()
            this.elementos['='].click()
            expect(this.$resultado.value.trim()).toBe('12')
        })
        it('Somar 13.45 + 9 deve resultar em 22.45', () => {
            this.elementos[1].click()
            this.elementos[3].click()
            this.elementos['.'].click()
            this.elementos[4].click()
            this.elementos[5].click()
            this.elementos['+'].click()
            this.elementos[9].click()
            this.elementos['='].click()
            expect(this.$resultado.value.trim()).toBe('22.45')
        })
        it('Somar 78 + 5.05 deve resultar em 83.05', () => {
            this.elementos[7].click()
            this.elementos[8].click()
            this.elementos['+'].click()
            this.elementos[5].click()
            this.elementos['.'].click()
            this.elementos[0].click()
            this.elementos[5].click()
            this.elementos['='].click()
            expect(this.$resultado.value.trim()).toBe('83.05')
        })
        it('Somar .5 + 8.32 deve resultar em 8.82', () => {
            this.elementos['.'].click()
            this.elementos[5].click()
            this.elementos['+'].click()
            this.elementos[8].click()
            this.elementos['.'].click()
            this.elementos[3].click()
            this.elementos[2].click()
            this.elementos['='].click()
            expect(this.$resultado.value.trim()).toBe('8.82')
        })
    })
    describe('Subtração', () => {
        it('Subtrair 7 - 5 deve resultar em 2', () => {
            this.elementos[7].click()
            this.elementos['-'].click()
            this.elementos[5].click()
            this.elementos['='].click()
            expect(this.$resultado.value.trim()).toBe('2')
        })
        it('Subtrair 13.4 - 9 deve resultar em 4.4', () => {
            this.elementos[1].click()
            this.elementos[3].click()
            this.elementos['.'].click()
            this.elementos[4].click()
            this.elementos['-'].click()
            this.elementos[9].click()
            this.elementos['='].click()
            expect(this.$resultado.value.trim()).toBe('4.4')
        })
        it('Subtrair 78 - 5.05 deve resultar em 73.05', () => {
            this.elementos[7].click()
            this.elementos[8].click()
            this.elementos['-'].click()
            this.elementos[5].click()
            this.elementos['.'].click()
            this.elementos[0].click()
            this.elementos[5].click()
            this.elementos['='].click()
            expect(this.$resultado.value.trim()).toBe('72.95')
        })
        it('Subtrair .5 - 8.32 deve resultar em -7.82', () => {
            this.elementos['.'].click()
            this.elementos[5].click()
            this.elementos['-'].click()
            this.elementos[8].click()
            this.elementos['.'].click()
            this.elementos[3].click()
            this.elementos[2].click()
            this.elementos['='].click()
            expect(this.$resultado.value.trim()).toBe('-7.82')
        })
    })
})
