describe('Decimais', () => {
    beforeAll(() => {
        this.elementos = carregarConteudo()
        this.$resultado = this.elementos['calc'].querySelector('input')
        initCalculadora()
    })
    beforeEach(() => {
        this.$resultado.value = ''
    })
    it('deve calcular normalmente sem nenhum decimal (7+5=12)', ()=>{
        this.elementos[7].click()
        this.elementos['+'].click()
        this.elementos[5].click()
        this.elementos['='].click()
        expect(this.$resultado.value.trim()).toBe('12')
    })
    it('deve calcular normalmente com um decimal a esquerda (7.3+8=15.3)', ()=>{
        this.elementos[7].click()
        this.elementos['.'].click()
        this.elementos[3].click()
        this.elementos['+'].click()
        this.elementos[8].click()
        this.elementos['='].click()
        expect(this.$resultado.value.trim()).toBe('15.3')
    })
    it('deve calcular normalmente com um decimal a direita (9+32.4=41.4)', ()=>{
        this.elementos[9].click()
        this.elementos['+'].click()
        this.elementos[3].click()
        this.elementos[2].click()
        this.elementos['.'].click()
        this.elementos[4].click()
        this.elementos['='].click()
        expect(this.$resultado.value.trim()).toBe('41.4')
    })
    it('deve calcular normalmente com dois decimais (.7+.8=1.5)', ()=>{
        this.elementos['.'].click()
        this.elementos[7].click()
        this.elementos['+'].click()
        this.elementos['.'].click()
        this.elementos[8].click()
        this.elementos['='].click()
        expect(this.$resultado.value.trim()).toBe('1.5')
    })
    it('deve ignorar se clicar no ponto mais de uma vez antes da operação (.7+8)', ()=>{
        this.elementos['.'].click()
        this.elementos[7].click()
        this.elementos['.'].click()
        this.elementos['+'].click()
        this.elementos[8].click()
        expect(this.$resultado.value).toBe('.7+8') 
    })
    it('deve ignorar se clicar no ponto mais de uma vez depois da operação (.7+8.3)', ()=>{
        this.elementos['.'].click()
        this.elementos[7].click()
        this.elementos['.'].click()
        this.elementos['+'].click()
        this.elementos[8].click()
        this.elementos['.'].click()
        this.elementos['.'].click()
        this.elementos[3].click()
        this.elementos['.'].click()
        expect(this.$resultado.value).toBe('.7+8.3') 
    })
})